export interface RegistryEntry {
  id:    number;
  title: string;
}

export const registry: RegistryEntry[] = [
  { id: 1,  title: 'empty first name blocks submission' },
  { id: 2,  title: 'empty last name blocks submission' },
  { id: 3,  title: 'malformed email blocks submission' },
  { id: 4,  title: 'empty date of birth blocks submission' },
  { id: 5,  title: 'empty phone blocks submission' },
  { id: 6,  title: 'weak password blocks submission' },
  { id: 7,  title: 'mismatched password confirmation blocks submission' },
  { id: 8,  title: 'unchecked terms blocks submission' },
  { id: 9,  title: 'everything empty flags multiple field errors' },
  { id: 10, title: 'empty country of residence blocks submission' },
  { id: 11, title: 'a new user signs up end-to-end' },
  { id: 12, title: 'empty username blocks login submission' },
  { id: 13, title: 'empty password blocks login submission' },
  { id: 14, title: 'wrong credentials leave the user signed out' },
  { id: 15, title: 'an existing user logs in with valid credentials' },
  { id: 16, title: 'an authenticated user completes a GA purchase paying by card via cybersource unified checkout' },
  { id: 17, title: 'an authenticated user completes a GA purchase paying by a 3DS card via cybersource unified checkout' },
  { id: 18, title: 'an authenticated user cancels the 3DS challenge and the payment fails' },
  { id: 19, title: 'an anonymous user is redirected to register when proceeding to checkout' },
  { id: 20, title: 'empty date of birth blocks submission when show_dob is enabled' },
  { id: 21, title: 'an authenticated user completes a GA purchase paying by tabby' },
  { id: 22, title: 'an authenticated user completes a GA purchase' },
  { id: 23, title: 'an authenticated user buys 3 GA tickets and admin fully refunds them' },
  { id: 24, title: 'an authenticated user buys 3 GA tickets and admin partially refunds one' },
  { id: 25, title: 'logout ends the session' },
  { id: 26, title: 'logout empties the cart' },
  { id: 27, title: 'addon is hidden on the addons page when available online is off' },
  { id: 28, title: 'addon is hidden on the addons page when addon is unpub' },
  { id: 29, title: 'addon is hidden on the addons page when all of its categories are web-unpublished' },
  { id: 30, title: 'addon renders sold-out when every category is out of stock' },
  { id: 31, title: 'addon category_min surfaces as data-min on the picker' },
  { id: 32, title: 'addon category_max surfaces as data-max on the picker' },
  { id: 33, title: 'addon picker with no constraints increments by 1 per click' },
  { id: 34, title: 'addon picker with category_min jumps to min on first inc' },
  { id: 35, title: 'addon picker with category_max caps qty at max' },
  { id: 36, title: 'addon picker with category_multiple_of increments in steps of N' },
  { id: 37, title: 'addon picker with min and multiple_of starts at max(min, multipleOf) then steps by multipleOf' },
  { id: 38, title: 'addon picker with min equal to max locks qty at exact value' },
  { id: 39, title: 'addon shows percent auto-discount badge and reduced price on the card' },
  { id: 40, title: 'addon shows fixed auto-discount badge and reduced price on the card' },
  { id: 41, title: 'addon shows real auto-discount badge with the flat pay-only price' },
  { id: 42, title: 'auto-apply badge suppressed when a restricted discount coexists on the addon' },
  { id: 43, title: "addon knows a promo-code discount exists but doesn't auto-apply it" },
  { id: 44, title: "addon discount scoped to one category doesn't leak to sibling categories" },
  { id: 45, title: "discount on the parent event doesn't leak into its addons" },
  { id: 46, title: 'global discount linked via discountlink applies to a scoped addon' },
  { id: 47, title: 'addon discount with discount_active=pos does not render on the web card' },
  { id: 48, title: 'fixed addon discount larger than the price floors the final price at 0' },
  { id: 49, title: 'addon promo-code fixed discount reduces price by flat amount after entry' },
  { id: 50, title: 'addon promo-code percent discount reduces price by the entered percentage' },
  { id: 51, title: 'addon promo-code real discount sets final price to the flat pay-only amount' },
  { id: 52, title: 'addon rejects a nonexistent promo code and leaves the price unchanged' },
  { id: 53, title: 'addon promo entry with empty code is a no-op on submit' },
  { id: 54, title: 'promo code valid for another addon is rejected on the current addon' },
  { id: 55, title: 'addon promo code with exhausted max_tickets counter is rejected' },
  { id: 56, title: 'addon discount with min_tickets is disabled until quantity reaches the threshold' },
  { id: 57, title: 'addon discount with max_tickets is disabled once quantity exceeds the threshold' },
  { id: 58, title: 'addon discount with multiple_of is enabled only at exact multiples of N' },
  { id: 59, title: 'addon discount picked on the addons page survives to the checkout preview' },
  { id: 60, title: 'purchased addon writes the chosen discount id to seat.seat_discount_id' },

  // pentest
  { id: 61, title: 'dotfile and metadata paths are denied with 403' },
  { id: 62, title: 'deleted files return 404' },
  { id: 63, title: 'public docs like security.txt are served with 200' },
  { id: 64, title: 'cert-renewal path stays reachable (not 403)' },
  { id: 65, title: '403 response body is the tenant branded page, not the Apache default' },
  { id: 66, title: 'POS registration cookie is set with Secure + HttpOnly + SameSite=Lax' },
];
